name: LiAuth
options:
  bundleIdPrefix: com.liwidale
  deploymentTarget:
    iOS: "16.0"
    macOS: "13.0"
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "2.0.0"
    CURRENT_PROJECT_VERSION: "1"
    CODE_SIGN_STYLE: Automatic

targets:
  LiAuth-iOS:
    type: application
    platform: iOS
    sources:
      - path: Sources
      - path: Resources
        optional: true
      - path: ../localization
        buildPhase: resources
        type: folder
      - path: ../assets/icons
        buildPhase: resources
        type: folder
      - path: ../assets/fonts/Inter-Regular.ttf
        buildPhase: resources
      - path: ../assets/fonts/Inter-Medium.ttf
        buildPhase: resources
      - path: ../assets/fonts/Inter-SemiBold.ttf
        buildPhase: resources
      - path: ../assets/fonts/Inter-Bold.ttf
        buildPhase: resources
      - path: ../assets/fonts/JetBrainsMono-SemiBold.ttf
        buildPhase: resources
      - path: ../branding/logo.png
        buildPhase: resources
      - path: ../branding/text.png
        buildPhase: resources
    dependencies:
      - framework: Frameworks/LiAuthCore.xcframework
        embed: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.liwidale.liauth
        INFOPLIST_FILE: Support/Info-iOS.plist
        CODE_SIGN_ENTITLEMENTS: Support/LiAuth.entitlements
        TARGETED_DEVICE_FAMILY: "1,2"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon

  LiAuth-macOS:
    type: application
    platform: macOS
    sources:
      - path: Sources
      - path: Resources
        optional: true
      - path: ../localization
        buildPhase: resources
        type: folder
      - path: ../assets/icons
        buildPhase: resources
        type: folder
      - path: ../assets/fonts/Inter-Regular.ttf
        buildPhase: resources
      - path: ../assets/fonts/Inter-Medium.ttf
        buildPhase: resources
      - path: ../assets/fonts/Inter-SemiBold.ttf
        buildPhase: resources
      - path: ../assets/fonts/Inter-Bold.ttf
        buildPhase: resources
      - path: ../assets/fonts/JetBrainsMono-SemiBold.ttf
        buildPhase: resources
      - path: ../branding/logo.png
        buildPhase: resources
      - path: ../branding/text.png
        buildPhase: resources
    dependencies:
      - framework: Frameworks/LiAuthCore.xcframework
        embed: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.liwidale.liauth
        INFOPLIST_FILE: Support/Info-macOS.plist
        CODE_SIGN_ENTITLEMENTS: Support/LiAuth.entitlements
        ENABLE_HARDENED_RUNTIME: true
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
